const potions = {
    attackPotion: {
        herb: 'guam leaf',
        secondary: 'eye of newt',
        exp: 25,
        isDefault: true,
    },
    antipoison: {
        herb: 'marrentill',
        secondary: 'unicorn horn dust',
        exp: 37.5,
        isDefault: true,
    },
    strengthPotion: {
        herb: 'tarromin',
        secondary: 'limpwurt root',
        exp: 50,
    },
    serum207: {
        herb: 'tarromin',
        secondary: 'ashes',
        exp: 50,
        isDefault: true,
    },
    compostPotion: {
        herb: 'harralander',
        secondary: 'volcanic ash',
        exp: 60,
    },
    restorePotion: {
        herb: 'harralander',
        secondary: "red spiders' eggs",
        exp: 62.5,
    },
    energyPotion: {
        herb: 'harralander',
        secondary: 'chocolate dust',
        exp: 67.5,
        isDefault: true,
    },
    defencePotion: {
        herb: 'ranarr weed',
        secondary: 'white berries',
        exp: 75,
    },
    agilityPotion: {
        herb: 'toadflax',
        secondary: 'toads legs',
        exp: 80,
    },
    combatPotion: {
        herb: 'harralander',
        secondary: 'goat horn dust',
        exp: 84,
    },
    prayerPotion: {
        herb: 'ranarr weed',
        secondary: 'snape grass',
        exp: 87.5,
        isDefault: true,
    },
    superAttack: {
        herb: 'irit leaf',
        secondary: 'eye of newt',
        exp: 100,
        isDefault: true,
    },
    superantipoison: {
        herb: 'irit leaf',
        secondary: 'unicorn horn dust',
        exp: 106.3,
    },
    fishingPotion: {
        herb: 'avantoe',
        secondary: 'eye of newt',
        exp: 112.5,
    },
    superEnergy: {
        herb: 'avantoe',
        secondary: 'mort myre fungus',
        exp: 117.5,
        isDefault: true,
    },
    hunterPotion: {
        herb: 'avantoe',
        secondary: 'kebbit teeth dust',
        exp: 120,
    },
    superStrength: {
        herb: 'kwuarm',
        secondary: 'limpwurt root',
        exp: 125,
        isDefault: true,
    },
    weaponPoison: {
        herb: 'kwuarm',
        secondary: 'dragon scale dust',
        exp: 137.5,
    },
    superRestore: {
        herb: 'snapdragon',
        secondary: "red spiders' eggs",
        exp: 142.5,
        isDefault: true,
    },
    sanfewSerum: {
        herb: 'snapdragon',
        secondary: ["red spiders' eggs", 'unicorn horn dust'],
        isSpecial: true,
        exp: 160,
    },
    superDefence: {
        herb: 'cadantine',
        secondary: 'white berries',
        exp: 150,
        isDefault: true,
    },
    'antidote+': {
        herb: 'toadflax',
        secondary: 'yew root',
        base: 'coconut milk',
        exp: 155,
        isSpecial: true,
    },
    antifirePotion: {
        herb: 'lantadyme',
        secondary: 'dragon scale dust',
        exp: 157.5,
    },
    rangingPotion: {
        herb: 'dwarf weed',
        secondary: 'wine of zamorak',
        exp: 162.5,
        isDefault: true,
    },
    'weaponPoison+': {
        secondary: ['cactus spine', "red spiders' eggs"],
        herb: 'coconut milk',
        isSpecial: true,
        exp: 165,
    },
    magicPotion: {
        herb: 'lantadyme',
        secondary: 'potato cactus',
        exp: 172.5,
        isDefault: true,
    },
    staminaPotion: {
        herb: 'super energy potion',
        secondary: 'amylase crystal',
        isSpecial: true,
        exp: 25.5,
    },
    zamorakBrew: {
        herb: 'torstol',
        secondary: 'jangerberries',
        exp: 175,
    },
    'antidote++': {
        herb: 'irit leaf',
        base: 'coconut milk',
        secondary: 'magic roots',
        isSpecial: true,
        exp: 177.5,
    },
    bastionPotion: {
        herb: 'cadantine',
        base: 'vial of blood',
        secondary: 'wine of zamorak',
        isSpecial: true,
        exp: 155,
    },
    battlemagePotion: {
        herb: 'cadantine',
        base: 'vial of blood',
        secondary: 'potato cactus',
        isSpecial: true,
        exp: 155,
    },
    saradominBrew: {
        herb: 'toadflax',
        secondary: 'crushed nest',
        exp: 180,
        isDefault: true,
    },
    'weaponPoison++': {
        herb: 'nightshade',
        base: 'coconut milk',
        secondary: 'poison ivy berries',
        isSpecial: true,
        exp: 190,
    },
    extendedAntifire: {
        herb: 'antifire potion',
        secondary: 'lava scale shard',
        isSpecial: true,
        exp: 110,
    },
    antivenom: {
        herb: 'antidote++',
        secondary: 'zulrah scale (5)',
        isSpecial: true,
        exp: 120,
    },
    superCombatPotion: {
        herb: 'torstol',
        secondary: ['super attack(4)', 'super strength(4)', 'super defence(4)'],
        exp: 150,
        isDefault: true,
    },
    superAntifirePotion: {
        herb: 'antifire potion',
        secondary: 'crushed superior dragon bones',
        isSpecial: true,
        exp: 130,
    },
    'antivenom+': {
        herb: 'torstol',
        secondary: 'anti venom',
        isSpecial: true,
        exp: 125,
    },
    extendedSuperAntifire: {
        herb: 'super antifire',
        secondary: 'lava scale shard',
        isSpecial: true,
        exp: 160,
    },
};

export default potions;
